### ISSUE TITLE
Question: How to run bitcoind with indexes on downloaded blockchain?

### ISSUE THREAD

**Issue by karelbilek** [bitpay/bitcoin#37]
Hello,

I have a blockchain downloaded with bitcoind 0.12.1 without the patch.

Now I want to run your patched version, but I don't want to re-download the whole blockchain again from the P2P network, since I already have it. How to tell your bitcoind to make the indexes on the existing blockchain?

**Comment by karelbilek** [comment]
Just running it with `-reindex` seems to be enough.

**Comment by gabegattis** [comment]
Just make sure that you remove -reindex before the next time you start your node or it will try to reindex again.
